# Path to text file containing graammar productions
grammar: "examples/grammars/ll1-simple.txt"
# String as space separated tokens
string: "a b"
# Parsing algorithm. Choices = ['ll1', 'lr0', 'slr1', 'lr1', 'lalr1']
parsing_algo: ll1
# Should the parsing table be exported ?
parsing-table: True
# Should the resultant syntax tree be visualized ?
vis-tree: True
# Should the resultant LR automaton be visualized ? (valid for LR parsing only)
# vis-automaton: True
# Should the parsing process be visualized ? (Will use `manim` for animation)
vis-parsing: True
# Quality of manim video. Choices = ['480p', '720p', '1080p', '1440p', '2160p']
manim-video-quality: "480p"

