remote_theme: pmarsceill/just-the-docs
color_scheme: mygreen

markdown: kramdown

title: yacv
description: Tools and libraries to run neural networks in Minecraft
baseurl: /yacv

search_enabled: true
permalink: pretty

footer_content: "Copyright &copy; 2020 Ashutosh Sathe. Distributed by a <a href=\"https://github.com/ashutoshbsathe/scarpet-nn/blob/master/LICENSE\">GPL v3 license.</a>"

ga_tracking: UA-163324683-1

aux_links:
  "ashutoshbsathe.github.io":
    - "https://ashutoshbsathe.github.io"
  "scarpet-nn on GitHub":
    - "https://github.com/ashutoshbsathe/scarpet-nn"

plugins:
  - jemoji
