remote_theme: pmarsceill/just-the-docs
color_scheme: mygreen

markdown: kramdown

title: yacv
description: Yet Another Compiler Visualizer
baseurl: /yacv

search_enabled: true
permalink: pretty

footer_content: "Copyright &copy; 2021 Ashutosh Sathe. Distributed by <a href=\"https://github.com/ashutoshbsathe/yacv/blob/master/LICENSE.md\">MIT license.</a>"

ga_tracking: UA-163324683-1

aux_links:
  "ashutoshbsathe.github.io":
    - "https://ashutoshbsathe.github.io"
  "yacv on GitHub":
    - "https://github.com/ashutoshbsathe/yacv"

plugins:
  - jemoji
